name: android-arm-cpu
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install attr
    - name: preflight
      run: ./scripts/.travis/preflight_arm.sh || echo "skip"
    - name: build
      run: export ANDROID_NDK=$ANDROID_HOME/ndk-bundle && ./scripts/build_android.sh