name: android-arm-cpu
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      SKIP: ${{ steps.preflight.outputs.SKIP }}
    steps:
    - uses: actions/checkout@v2
    - name: Preflight
      id: preflight
      run: |
        echo '::set-output name=SKIP::FALSE'
        ./scripts/.travis/preflight_arm.sh || echo '::set-output name=SKIP::TRUE'
        echo ${{ outputs.SKIP }}

  android:
    needs: [setup]
    if: ${{ needs.setup.outputs.SKIP != 'TRUE' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install attr
    - name: build
      run: export ANDROID_NDK=$ANDROID_HOME/ndk-bundle && ./scripts/build_android.sh
