name: ios-cpu
on:
  push:
    branches:
      - master
    paths:
      - 'include/tnn/**'
      - 'platforms/ios/**'
      - 'scripts/build_ios.sh'
      - 'source/tnn/**'
      - '!source/tnn/device/**'
      - 'source/tnn/device/arm/**'
      - 'source/tnn/device/metal/**'
      - '!source/tnn/extern_wrapper/**'
  pull_request:
    branches:
      - master
    paths:
      - 'include/tnn/**'
      - 'platforms/ios/**'
      - 'scripts/build_ios.sh'
      - 'source/tnn/**'
      - '!source/tnn/device/**'
      - 'source/tnn/device/arm/**'
      - 'source/tnn/device/metal/**'
      - '!source/tnn/extern_wrapper/**'
jobs:
  ios-iphone-os:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./scripts/build_ios.sh
