name: linux-x86-cpu-gcc
on:
  push:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/tnn/**'
      - 'scripts/build_linux.sh'
      - 'source/tnn/**'
      - '!source/tnn/device/**'
      - 'source/tnn/device/cpu/**'
      - 'source/tnn/device/x86/**'
  pull_request:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/tnn/**'
      - 'scripts/build_linux.sh'
      - 'source/tnn/**'
      - '!source/tnn/device/**'
      - 'source/tnn/device/cpu/**'
      - 'source/tnn/device/x86/**'
jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: gcc-multilib
      run: sudo apt-get install gcc-multilib g++-multilib libprotobuf-dev protobuf-compiler
    - name: build
      run: ./scripts/build_linux.sh
