name: macos-x64-cpu
on:
  push:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/tnn/**'
      - 'scripts/build_linux.sh'
      - 'source/tnn/**'
      - '!source/tnn/device/**'
      - 'source/tnn/device/cpu/**'
      - 'source/tnn/device/x86/**'
  pull_request:
    branches:
      - master
    paths:
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/tnn/**'
      - 'scripts/build_linux.sh'
      - 'source/tnn/**'
      - '!source/tnn/device/**'
      - 'source/tnn/device/cpu/**'
      - 'source/tnn/device/x86/**'
jobs:
  macos-clang:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: protobuf
      run: brew install protobuf opencv3
    - name: build
      run: ./scripts/build_macos.sh
